apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: github-tests-go-tshhlvec
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap-test-organization-jk/github-tests-go-tshhlvec:4a4d0be46c37ba5bf2db57f244d611f4e7fb4037
        name: container-image  
