apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: github-tests-go-tshhlvec
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/github-tests-go-tshhlvec:dea346dd71c3b174ebd05fb7c1cc9a08d0aa6379
          name: container-image
